### PR TITLE
Feature/check existing exporters

### PR DESCRIPTION
**Pull request by honarkhah**

### CODE REVIEW

**Comment by honarkhah** [comment]
@Voronenko  Please check the test runner! 

PLAY RECAP *********************************************************************
localhost                  : ok=138  changed=66   unreachable=0    failed=0    skipped=37   rescued=0    ignored=1 

but return fail!!

**Comment by honarkhah** [comment]
I think there is an issue with loop_count

**Comment by Voronenko** [comment]
@honarkhah   
Step failed is idempotency (we do not see steps)
```
$ sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} | grep -q 'unreachable=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
```

This means that second run over previously provisioned instance fails.

I will be introducing molecule development environment soon, thus will rebase  your PR to that branch, so we can take a look

**Comment by honarkhah** [comment]
Thanks.

**Pull request merged**
