### PR TITLE
chore(typo)

### PR DESCRIPTION
**Pull request by adriagalin**
Hi!

first of all, thanks for this good work.

I found a typo in the apache exporter yaml.

Thank you.

### CODE REVIEW

**Comment by Voronenko** [comment]
@adriagalin Thank you for the input.

Perhaps you can state original issue you are trying to solve, because scope of PR goes above of mentioned "chores".

In setups this role is used on, usually each exporter runs on each own user (and in simpler setup it is dropped to shared prometheus one) 

That's why we have blocks you've removed
```
    become: yes
    become_user: "{{ apache_exporter_user }}"
```

2)  Try to ensure that you have a green travis build too (in that scenario not your fault - sql exporter moved forward, but still)

**Comment by adriagalin** [comment]
@Voronenko thanks for the feedback. I was testing things and I pushed it accidentally, sorry for that. I'm going to remove it

**Comment by adriagalin** [comment]
@Voronenko I just fixed it but the test fails for another reason, and only fail for Fedora 28.

https://travis-ci.org/softasap/sa-prometheus-exporters/builds/400178828 -> [Errno 13] Permission denied.

When you can, could you check it?

Thank you!

**Comment by Voronenko** [comment]
yeah, sure

**Comment by Voronenko** [comment]
Thanks once again

**Comment by adriagalin** [comment]
@Voronenko thank you for your great job! ;)

**Comment by Voronenko** [comment]
If you know some useful exporters - let me know in form of issues or PRs :)

**Pull request merged**
